# Generated by Django 4.2.4 on 2023-09-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=100)),
                ('mcontact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
